check:
    global:
        statements: 50
        lines: 50
        branches: 50
        functions: 50
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
